# Pandas

The `numpy` module is excellent for numerical computations, but to handle missing data or arrays with mixed types takes more work. The `pandas` module is currently the most widely used tool for data manipulation, providing high-performance, easy-to-use data structures and advanced data analysis tools.

In particular `pandas` features:

* A fast and efficient "DataFrame" object for data manipulation with integrated indexing;
* Tools for reading and writing data between in-memory data structures and different formats (CSV, Excel, SQL, HDF5);
* Intelligent data alignment and integrated handling of missing data;
* Intelligent label-based slicing, fancy indexing, and subsetting of large data sets;
* Aggregating or transforming data with a powerful "group-by" engine; 
* High performance merging and joining of data sets;
* Hierarchical axis indexing provides an intuitive way of working with high-dimensional data in a lower-dimensional data structure;
* Time series-functionalities;
* Highly optimized for performance, with critical code paths written in Cython or C.

In [1]:
import pandas as pd
import numpy as np

## Series

Series are completely equivalent to 1D array but with axis labels and the possibility to store heterogeneous elements. Of paramount importance are the time-series, used to define time evolutions of a phenomenon.

In [2]:
from string import ascii_lowercase as letters

# Creating a series, accessing indexes, values and values by their index 
xs = pd.Series(np.arange(10)*0.5, index=tuple(letters[:10]))
print ("xs:", xs,'\n')
print ("xs indexes:",xs.index,'\n')
# Values of the Series are actually a numpy array
print ("xs values:", xs.values, type(xs.values),'\n')
print (xs['f'], xs.f, xs.h, '\n')
print (xs[['d', 'f', 'h']], '\n')
print (type(xs[['d', 'f', 'h']]), '\n')

xs: a    0.0
b    0.5
c    1.0
d    1.5
e    2.0
f    2.5
g    3.0
h    3.5
i    4.0
j    4.5
dtype: float64

xs indexes: Index(['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j'], dtype='object')

xs values: [0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5] <class 'numpy.ndarray'>

2.5 2.5 3.5

d    1.5
f    2.5
h    3.5
dtype: float64

<class 'pandas.core.series.Series'>

In [3]:
# Extracting elements and operations: same as numpy array
print (xs[:3],'\n')
print (xs[7:], '\n')
print (xs[::3], '\n')
print (xs[xs>3], '\n')
print (np.exp(xs), '\n')
print (np.mean(xs), np.std(xs), '\n')

a    0.0
b    0.5
c    1.0
dtype: float64

h    3.5
i    4.0
j    4.5
dtype: float64

a    0.0
d    1.5
g    3.0
j    4.5
dtype: float64

h    3.5
i    4.0
j    4.5
dtype: float64

a     1.000000
b     1.648721
c     2.718282
d     4.481689
e     7.389056
f    12.182494
g    20.085537
h    33.115452
i    54.598150
j    90.017131
dtype: float64

2.25 1.4361406616345072

In [4]:
# Series can be created from python dictionary too.
# Not that the elements can be whatever!
d = {'b' : 1, 'a' : 'cat', 'c' : [2,3]}
pd.Series(d)

b         1
a       cat
c    [2, 3]
dtype: object

A key difference between Series and ndarray is that operations between Series automatically align the data based on label. Thus, you can write computations without considering whether the Series involved have the same labels.

In [5]:
s = pd.Series(np.random.randn(5), index=tuple(letters[:5]))
print(s)
s = s[1:] + s[:-1]
print(s)

a    0.371385
b   -0.659692
c    1.186042
d   -0.569304
e   -1.694678
dtype: float64
a         NaN
b   -1.319383
c    2.372084
d   -1.138607
e         NaN
dtype: float64

### Time series

Time series are very often used to profile the behaviour of a quantity as a function of time. Pandas has a special index for that, `DatetimeIndex`, that can be created e.g. with the function `pd.data_range()`

In [6]:
# to define a date, the datetime module is very useful
import datetime as dt
date = dt.date.today()
print(date)

date = dt.datetime(2025,11,26,10,45,10,15)
print (date)

# otherwise, several notations are interpreted too
date = 'Nov 26 2025'
# or alternatively
#date = '26/11/2025 10:45:00'
print (date)

days = pd.date_range(date, periods=7, freq='D')
print (days)

seconds = pd.date_range(date, periods=3600, freq='s')
print (seconds)

2026-01-05
2025-11-26 10:45:10.000015
Nov 26 2025
DatetimeIndex(['2025-11-26', '2025-11-27', '2025-11-28', '2025-11-29',
               '2025-11-30', '2025-12-01', '2025-12-02'],
              dtype='datetime64[ns]', freq='D')
DatetimeIndex(['2025-11-26 00:00:00', '2025-11-26 00:00:01',
               '2025-11-26 00:00:02', '2025-11-26 00:00:03',
               '2025-11-26 00:00:04', '2025-11-26 00:00:05',
               '2025-11-26 00:00:06', '2025-11-26 00:00:07',
               '2025-11-26 00:00:08', '2025-11-26 00:00:09',
               ...
               '2025-11-26 00:59:50', '2025-11-26 00:59:51',
               '2025-11-26 00:59:52', '2025-11-26 00:59:53',
               '2025-11-26 00:59:54', '2025-11-26 00:59:55',
               '2025-11-26 00:59:56', '2025-11-26 00:59:57',
               '2025-11-26 00:59:58', '2025-11-26 00:59:59'],
              dtype='datetime64[ns]', length=3600, freq='s')

To learn more about the frequency strings, please see this [link](http://pandas.pydata.org/pandas-docs/stable/timeseries.html#offset-aliases)


Timestamped data is the most basic type of time series data that associates values with points in time. For pandas objects it means using the points in time.

functions like `pd.to_datetime` can be used, for instance, when reading information as string from a dataset.

Timestamp is the pandas equivalent of python’s Datetime and is interchangeable with it in most cases.

In [7]:
tstamp = pd.Timestamp(dt.datetime(2020, 11, 9))

# internally it counts the nanoseconds from January 1st 19
#tstamp = pd.Timestamp(dt.datetime(1970, 1, 1, 0, 0, 0, 1))
print(tstamp.value)

# when creating a timestamp the format can be explicitly passed
ts = pd.to_datetime('2010/11/12', format='%Y/%m/%d')
print (type(ts))
print (ts.value)
ts = pd.to_datetime('12-11-2010 00:00', format='%d-%m-%Y %H:%M')
print (ts)
print (ts.value)

1604880000000000000
<class 'pandas._libs.tslibs.timestamps.Timestamp'>
1289520000000000000
2010-11-12 00:00:00
1289520000000000000

A standard series can be created and (range of) elements can be used as indexes

In [8]:
tseries = pd.Series(np.random.normal(10, 1, len(days)), index=days)
# Extracting elements
print (tseries[0:4], '\n')
print (tseries['2025-11-26':'2025-12-02'], '\n') # Note - includes end time

2025-11-26    10.692112
2025-11-27    11.041429
2025-11-28     9.668883
2025-11-29    10.348505
Freq: D, dtype: float64

2025-11-26    10.692112
2025-11-27    11.041429
2025-11-28     9.668883
2025-11-29    10.348505
2025-11-30    10.999268
2025-12-01     9.828493
2025-12-02    10.795097
Freq: D, dtype: float64

`pd.to_datetime` can also be used to create a `DatetimeIndex`:

In [9]:
pd.to_datetime([1, 2, 3, 4], unit='D', origin=pd.Timestamp('1980-02-03'))

DatetimeIndex(['1980-02-04', '1980-02-05', '1980-02-06', '1980-02-07'], dtype='datetime64[ns]', freq=None)

## DataFrame

A pandas DataFrame is like a simple tabular spreadsheet. For future reference (or for people already familiar with R), a pandas DataFrame is very similar to the R DataFrame.

Each column in a DataFrame is a Series object.

The element can be whatever, missing data are dealt with too (as NaN)

### DataFrame creation

A DataFrame can be created implicitly, with, e.g., a DatatimeIndex object as index:

In [10]:
entries=10
dates=pd.date_range('11/26/2025 10:45:00',freq='h', periods=entries)
df = pd.DataFrame(np.random.randn(entries,4), index=dates, columns=['A','B','C','D'])
df

                            A         B         C         D
2025-11-26 10:45:00  0.515840 -1.034299 -0.569374  1.132976
2025-11-26 11:45:00  0.960620  0.195759 -0.525286  1.262964
2025-11-26 12:45:00  0.713676 -0.345756  0.603780 -0.447710
2025-11-26 13:45:00 -0.348682 -0.414287 -1.066185 -1.312592
2025-11-26 14:45:00 -1.827368  0.026077 -0.646162  0.924107
2025-11-26 15:45:00  0.414432 -0.608723 -0.084327 -3.111225
2025-11-26 16:45:00 -0.859137 -0.733867  0.286232  0.212150
2025-11-26 17:45:00 -0.723186 -0.248101  0.538455 -0.710239
2025-11-26 18:45:00 -0.773866  0.730625  1.790614 -0.008055
2025-11-26 19:45:00 -0.709735  0.069013  0.142754  0.428850

or by means of a dictionary:

In [11]:
df2 = pd.DataFrame(
    { 'A' : 1.,
      'B' : pd.Timestamp('20130102'),
      'C' : pd.Series(1,index=range(4),dtype='float32'),
      'D' : np.arange(7,11),
      'E' : pd.Categorical(["test","train","test","train"]),
    }
    )
df2

# check what happens if D and E had different lenghts

     A          B    C   D      E
0  1.0 2013-01-02  1.0   7   test
1  1.0 2013-01-02  1.0   8  train
2  1.0 2013-01-02  1.0   9   test
3  1.0 2013-01-02  1.0  10  train

### Viewing Data

In [12]:
df.head(2)

                           A         B         C         D
2025-11-26 10:45:00  0.51584 -1.034299 -0.569374  1.132976
2025-11-26 11:45:00  0.96062  0.195759 -0.525286  1.262964

In [13]:
df.tail(4)

                            A         B         C         D
2025-11-26 16:45:00 -0.859137 -0.733867  0.286232  0.212150
2025-11-26 17:45:00 -0.723186 -0.248101  0.538455 -0.710239
2025-11-26 18:45:00 -0.773866  0.730625  1.790614 -0.008055
2025-11-26 19:45:00 -0.709735  0.069013  0.142754  0.428850

In [14]:
df.index

DatetimeIndex(['2025-11-26 10:45:00', '2025-11-26 11:45:00',
               '2025-11-26 12:45:00', '2025-11-26 13:45:00',
               '2025-11-26 14:45:00', '2025-11-26 15:45:00',
               '2025-11-26 16:45:00', '2025-11-26 17:45:00',
               '2025-11-26 18:45:00', '2025-11-26 19:45:00'],
              dtype='datetime64[ns]', freq='h')

In [15]:
df.columns

Index(['A', 'B', 'C', 'D'], dtype='object')

In [16]:
df.values

array([[ 0.51584021, -1.03429944, -0.56937391,  1.1329757 ],
       [ 0.96061991,  0.19575854, -0.52528563,  1.26296395],
       [ 0.71367637, -0.34575611,  0.60378015, -0.44770989],
       [-0.34868205, -0.41428675, -1.06618507, -1.31259217],
       [-1.82736817,  0.02607661, -0.64616193,  0.92410705],
       [ 0.41443174, -0.60872292, -0.08432664, -3.11122462],
       [-0.85913676, -0.73386701,  0.28623185,  0.21215033],
       [-0.72318553, -0.24810132,  0.53845497, -0.71023925],
       [-0.77386561,  0.73062525,  1.79061362, -0.00805548],
       [-0.70973491,  0.06901347,  0.14275388,  0.42884977]])

In [17]:
df.describe()

               A          B          C          D
count  10.000000  10.000000  10.000000  10.000000
mean   -0.263740  -0.236356   0.047050  -0.162877
std     0.881850   0.511050   0.823438   1.325136
min    -1.827368  -1.034299  -1.066185  -3.111225
25%    -0.761196  -0.560114  -0.558352  -0.644607
50%    -0.529208  -0.296929   0.029214   0.102047
75%     0.490488   0.058279   0.475399   0.800293
max     0.960620   0.730625   1.790614   1.262964

In [18]:
df.T

,2025-11-26 10:45:00,2025-11-26 11:45:00,2025-11-26 12:45:00,2025-11-26 13:45:00,2025-11-26 14:45:00,2025-11-26 15:45:00,2025-11-26 16:45:00,2025-11-26 17:45:00,2025-11-26 18:45:00,2025-11-26 19:45:00
A,0.515840,0.960620,0.713676,-0.348682,-1.827368,0.414432,-0.859137,-0.723186,-0.773866,-0.709735
B,-1.034299,0.195759,-0.345756,-0.414287,0.026077,-0.608723,-0.733867,-0.248101,0.730625,0.069013
C,-0.569374,-0.525286,0.603780,-1.066185,-0.646162,-0.084327,0.286232,0.538455,1.790614,0.142754
D,1.132976,1.262964,-0.447710,-1.312592,0.924107,-3.111225,0.212150,-0.710239,-0.008055,0.428850

In [19]:
df.sort_index(axis=0,ascending=False)

                            A         B         C         D
2025-11-26 19:45:00 -0.709735  0.069013  0.142754  0.428850
2025-11-26 18:45:00 -0.773866  0.730625  1.790614 -0.008055
2025-11-26 17:45:00 -0.723186 -0.248101  0.538455 -0.710239
2025-11-26 16:45:00 -0.859137 -0.733867  0.286232  0.212150
2025-11-26 15:45:00  0.414432 -0.608723 -0.084327 -3.111225
2025-11-26 14:45:00 -1.827368  0.026077 -0.646162  0.924107
2025-11-26 13:45:00 -0.348682 -0.414287 -1.066185 -1.312592
2025-11-26 12:45:00  0.713676 -0.345756  0.603780 -0.447710
2025-11-26 11:45:00  0.960620  0.195759 -0.525286  1.262964
2025-11-26 10:45:00  0.515840 -1.034299 -0.569374  1.132976

In [20]:
df.sort_values(by="C")

                            A         B         C         D
2025-11-26 13:45:00 -0.348682 -0.414287 -1.066185 -1.312592
2025-11-26 14:45:00 -1.827368  0.026077 -0.646162  0.924107
2025-11-26 10:45:00  0.515840 -1.034299 -0.569374  1.132976
2025-11-26 11:45:00  0.960620  0.195759 -0.525286  1.262964
2025-11-26 15:45:00  0.414432 -0.608723 -0.084327 -3.111225
2025-11-26 19:45:00 -0.709735  0.069013  0.142754  0.428850
2025-11-26 16:45:00 -0.859137 -0.733867  0.286232  0.212150
2025-11-26 17:45:00 -0.723186 -0.248101  0.538455 -0.710239
2025-11-26 12:45:00  0.713676 -0.345756  0.603780 -0.447710
2025-11-26 18:45:00 -0.773866  0.730625  1.790614 -0.008055

## Selection

### Getting slices

The following show how to get part of the DataFrame (i.e. not just the elements)

In [21]:
## standard and safe
print (df['A'],'\n')

## equivalent but dangerous (imagine blank spaces in the name of the column..)
print (df.A)

2025-11-26 10:45:00    0.515840
2025-11-26 11:45:00    0.960620
2025-11-26 12:45:00    0.713676
2025-11-26 13:45:00   -0.348682
2025-11-26 14:45:00   -1.827368
2025-11-26 15:45:00    0.414432
2025-11-26 16:45:00   -0.859137
2025-11-26 17:45:00   -0.723186
2025-11-26 18:45:00   -0.773866
2025-11-26 19:45:00   -0.709735
Freq: h, Name: A, dtype: float64

2025-11-26 10:45:00    0.515840
2025-11-26 11:45:00    0.960620
2025-11-26 12:45:00    0.713676
2025-11-26 13:45:00   -0.348682
2025-11-26 14:45:00   -1.827368
2025-11-26 15:45:00    0.414432
2025-11-26 16:45:00   -0.859137
2025-11-26 17:45:00   -0.723186
2025-11-26 18:45:00   -0.773866
2025-11-26 19:45:00   -0.709735
Freq: h, Name: A, dtype: float64

In [22]:
# selecting rows by counting
print (df[0:3])

# or by index
print (df["2025-11-26 10:45:00":"2025-11-26 12:45:00"])

                            A         B         C         D
2025-11-26 10:45:00  0.515840 -1.034299 -0.569374  1.132976
2025-11-26 11:45:00  0.960620  0.195759 -0.525286  1.262964
2025-11-26 12:45:00  0.713676 -0.345756  0.603780 -0.447710
                            A         B         C         D
2025-11-26 10:45:00  0.515840 -1.034299 -0.569374  1.132976
2025-11-26 11:45:00  0.960620  0.195759 -0.525286  1.262964
2025-11-26 12:45:00  0.713676 -0.345756  0.603780 -0.447710

### Selection by label

In [23]:
# getting a cross section (part of the DataFrame) using a label
df.loc[dates[0]]

A    0.515840
B   -1.034299
C   -0.569374
D    1.132976
Name: 2025-11-26 10:45:00, dtype: float64

In [24]:
# selecting on a multi-axis by label:
df.loc[:,['A','B']]
#a=df.loc[:,['A','B']]

                            A         B
2025-11-26 10:45:00  0.515840 -1.034299
2025-11-26 11:45:00  0.960620  0.195759
2025-11-26 12:45:00  0.713676 -0.345756
2025-11-26 13:45:00 -0.348682 -0.414287
2025-11-26 14:45:00 -1.827368  0.026077
2025-11-26 15:45:00  0.414432 -0.608723
2025-11-26 16:45:00 -0.859137 -0.733867
2025-11-26 17:45:00 -0.723186 -0.248101
2025-11-26 18:45:00 -0.773866  0.730625
2025-11-26 19:45:00 -0.709735  0.069013

In [25]:
# showing label slicing, both endpoints are included:
df.loc['2025-11-26 14:45:00':'2025-11-26 16:45:00',['A','B']]

                            A         B
2025-11-26 14:45:00 -1.827368  0.026077
2025-11-26 15:45:00  0.414432 -0.608723
2025-11-26 16:45:00 -0.859137 -0.733867

In [26]:
# getting an individual element
print (df.loc[dates[1],'A'])

# equivalently
print (df.at[dates[1],'A'])

0.9606199105515558
0.9606199105515558

### Selecting by position

In [27]:
# select via the position of the passed integers:
print (df.iloc[3],'\n')

# notation similar to numpy/python
print (df.iloc[3:5,0:2])

A   -0.348682
B   -0.414287
C   -1.066185
D   -1.312592
Name: 2025-11-26 13:45:00, dtype: float64

                            A         B
2025-11-26 13:45:00 -0.348682 -0.414287
2025-11-26 14:45:00 -1.827368  0.026077

In [28]:
# selecting raws 1,2 and 4 for columns 0 and 2
df.iloc[[1,2,4],[0,2]]

                            A         C
2025-11-26 11:45:00  0.960620 -0.525286
2025-11-26 12:45:00  0.713676  0.603780
2025-11-26 14:45:00 -1.827368 -0.646162

In [29]:
# slicing rows explicitly
print (df.iloc[1:3,:],'\n')

# slicing columns explicitly
print (df.iloc[:,1:3])

# selecting an individual element by position
print(df.iloc[1,1])

                            A         B         C         D
2025-11-26 11:45:00  0.960620  0.195759 -0.525286  1.262964
2025-11-26 12:45:00  0.713676 -0.345756  0.603780 -0.447710

                            B         C
2025-11-26 10:45:00 -1.034299 -0.569374
2025-11-26 11:45:00  0.195759 -0.525286
2025-11-26 12:45:00 -0.345756  0.603780
2025-11-26 13:45:00 -0.414287 -1.066185
2025-11-26 14:45:00  0.026077 -0.646162
2025-11-26 15:45:00 -0.608723 -0.084327
2025-11-26 16:45:00 -0.733867  0.286232
2025-11-26 17:45:00 -0.248101  0.538455
2025-11-26 18:45:00  0.730625  1.790614
2025-11-26 19:45:00  0.069013  0.142754
0.19575854491738523

### Boolean index

Very powerful way of filtering out data with certain features. Notation is very similar to numpy arrays.

In [30]:
# Filter by a boolean condition on the values of a single column
df[df['B'] > 0]

                            A         B         C         D
2025-11-26 11:45:00  0.960620  0.195759 -0.525286  1.262964
2025-11-26 14:45:00 -1.827368  0.026077 -0.646162  0.924107
2025-11-26 18:45:00 -0.773866  0.730625  1.790614 -0.008055
2025-11-26 19:45:00 -0.709735  0.069013  0.142754  0.428850

In [31]:
# Selecting on the basis of boolean conditions applied to the whole DataFrame
df[df>0]

# a DataFrame with the same shape is returned, with NaN's where condition is not met

                            A         B         C         D
2025-11-26 10:45:00  0.515840       NaN       NaN  1.132976
2025-11-26 11:45:00  0.960620  0.195759       NaN  1.262964
2025-11-26 12:45:00  0.713676       NaN  0.603780       NaN
2025-11-26 13:45:00       NaN       NaN       NaN       NaN
2025-11-26 14:45:00       NaN  0.026077       NaN  0.924107
2025-11-26 15:45:00  0.414432       NaN       NaN       NaN
2025-11-26 16:45:00       NaN       NaN  0.286232  0.212150
2025-11-26 17:45:00       NaN       NaN  0.538455       NaN
2025-11-26 18:45:00       NaN  0.730625  1.790614       NaN
2025-11-26 19:45:00       NaN  0.069013  0.142754  0.428850

### Setting

Combination of selection and setting of values

In [32]:
# setting values by label (same as by position)
df.at[dates[0],'A'] = 0

# setting and assigning a numpy array
df.loc[:,'D'] = np.array([5] * len(df))

# defining a brend new column
df['E'] = np.arange(len(df))*0.5

# defining a brend new column by means of a pd.Series: indexes must be the same!
df['E prime'] = pd.Series(np.arange(len(df))*2, index=df.index)

df

                            A         B         C    D    E  E prime
2025-11-26 10:45:00  0.000000 -1.034299 -0.569374  5.0  0.0        0
2025-11-26 11:45:00  0.960620  0.195759 -0.525286  5.0  0.5        2
2025-11-26 12:45:00  0.713676 -0.345756  0.603780  5.0  1.0        4
2025-11-26 13:45:00 -0.348682 -0.414287 -1.066185  5.0  1.5        6
2025-11-26 14:45:00 -1.827368  0.026077 -0.646162  5.0  2.0        8
2025-11-26 15:45:00  0.414432 -0.608723 -0.084327  5.0  2.5       10
2025-11-26 16:45:00 -0.859137 -0.733867  0.286232  5.0  3.0       12
2025-11-26 17:45:00 -0.723186 -0.248101  0.538455  5.0  3.5       14
2025-11-26 18:45:00 -0.773866  0.730625  1.790614  5.0  4.0       16
2025-11-26 19:45:00 -0.709735  0.069013  0.142754  5.0  4.5       18

In [33]:
def dcos(theta):
    theta = theta*(np.pi/180)
    return np.cos(theta)
 
df['cosine'] = pd.Series(df["E"].apply(dcos), index=df.index)
df

                            A         B         C    D    E  E prime    cosine
2025-11-26 10:45:00  0.000000 -1.034299 -0.569374  5.0  0.0        0  1.000000
2025-11-26 11:45:00  0.960620  0.195759 -0.525286  5.0  0.5        2  0.999962
2025-11-26 12:45:00  0.713676 -0.345756  0.603780  5.0  1.0        4  0.999848
2025-11-26 13:45:00 -0.348682 -0.414287 -1.066185  5.0  1.5        6  0.999657
2025-11-26 14:45:00 -1.827368  0.026077 -0.646162  5.0  2.0        8  0.999391
2025-11-26 15:45:00  0.414432 -0.608723 -0.084327  5.0  2.5       10  0.999048
2025-11-26 16:45:00 -0.859137 -0.733867  0.286232  5.0  3.0       12  0.998630
2025-11-26 17:45:00 -0.723186 -0.248101  0.538455  5.0  3.5       14  0.998135
2025-11-26 18:45:00 -0.773866  0.730625  1.790614  5.0  4.0       16  0.997564
2025-11-26 19:45:00 -0.709735  0.069013  0.142754  5.0  4.5       18  0.996917

In [34]:
# another example of global setting
df2=df.copy()

df2[df2>0] = -df2
df2

                            A         B         C    D    E  E prime    cosine
2025-11-26 10:45:00  0.000000 -1.034299 -0.569374 -5.0  0.0        0 -1.000000
2025-11-26 11:45:00 -0.960620 -0.195759 -0.525286 -5.0 -0.5       -2 -0.999962
2025-11-26 12:45:00 -0.713676 -0.345756 -0.603780 -5.0 -1.0       -4 -0.999848
2025-11-26 13:45:00 -0.348682 -0.414287 -1.066185 -5.0 -1.5       -6 -0.999657
2025-11-26 14:45:00 -1.827368 -0.026077 -0.646162 -5.0 -2.0       -8 -0.999391
2025-11-26 15:45:00 -0.414432 -0.608723 -0.084327 -5.0 -2.5      -10 -0.999048
2025-11-26 16:45:00 -0.859137 -0.733867 -0.286232 -5.0 -3.0      -12 -0.998630
2025-11-26 17:45:00 -0.723186 -0.248101 -0.538455 -5.0 -3.5      -14 -0.998135
2025-11-26 18:45:00 -0.773866 -0.730625 -1.790614 -5.0 -4.0      -16 -0.997564
2025-11-26 19:45:00 -0.709735 -0.069013 -0.142754 -5.0 -4.5      -18 -0.996917

### Are you dealing with a Copy or a View?

In general is hard to tell..

In [35]:
dfd = pd.DataFrame({'a': [1, 2, 3], 'b': [4, 5, 6]})

# This is likely a view
subset = dfd.loc[0:1, 'a']  
subset[0] = 100  # May affect `df`

print (dfd)

# This is a copy
subset = dfd.loc[[0, 1], 'a']  
subset[0] = 200  # Does NOT affect `df`

print (dfd)

     a  b
0  100  4
1    2  5
2    3  6
     a  b
0  100  4
1    2  5
2    3  6

The behaviour depend on the version of Pandas and on the version of Numpy that given version of Pandas depends upon. Since Pandas 1.5 "Copy-on-Write" (CoW) is (optionally) available and as of Pandas 3.0 will be the default. 

With CoW chained assignemt will never work; in the following example, the view `dfd["a"]` and `df` itself are modified in one step. This will lead to a `ChainedAssignemntError`

In [36]:
dfd["a"][dfd["b"] > 5] = 100
dfd

/tmp/ipykernel_61146/449088826.py:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  dfd["a"][dfd["b"] > 5] = 100

     a  b
0  100  4
1    2  5
2  100  6

With copy on write this can be done by using `loc`

In [37]:
dfd.loc[dfd["b"] > 5, "a"] = 200
dfd

     a  b
0  100  4
1    2  5
2  200  6

### Dropping

N.B.: dropping doesn't act permanently on the DataFrame, i.e. to get that do :
```python
df = df.drop(....)
```

In [38]:
# Dropping by column
df.drop(['E prime'], axis=1)

#which is equivalent to
new_df=df.drop(columns=['E prime'])
new_df

                            A         B         C    D    E    cosine
2025-11-26 10:45:00  0.000000 -1.034299 -0.569374  5.0  0.0  1.000000
2025-11-26 11:45:00  0.960620  0.195759 -0.525286  5.0  0.5  0.999962
2025-11-26 12:45:00  0.713676 -0.345756  0.603780  5.0  1.0  0.999848
2025-11-26 13:45:00 -0.348682 -0.414287 -1.066185  5.0  1.5  0.999657
2025-11-26 14:45:00 -1.827368  0.026077 -0.646162  5.0  2.0  0.999391
2025-11-26 15:45:00  0.414432 -0.608723 -0.084327  5.0  2.5  0.999048
2025-11-26 16:45:00 -0.859137 -0.733867  0.286232  5.0  3.0  0.998630
2025-11-26 17:45:00 -0.723186 -0.248101  0.538455  5.0  3.5  0.998135
2025-11-26 18:45:00 -0.773866  0.730625  1.790614  5.0  4.0  0.997564
2025-11-26 19:45:00 -0.709735  0.069013  0.142754  5.0  4.5  0.996917

In [39]:
# Dropping by raws
# safe and always working
df.drop(df.index[[1,2,3,4]])

                            A         B         C    D    E  E prime    cosine
2025-11-26 10:45:00  0.000000 -1.034299 -0.569374  5.0  0.0        0  1.000000
2025-11-26 15:45:00  0.414432 -0.608723 -0.084327  5.0  2.5       10  0.999048
2025-11-26 16:45:00 -0.859137 -0.733867  0.286232  5.0  3.0       12  0.998630
2025-11-26 17:45:00 -0.723186 -0.248101  0.538455  5.0  3.5       14  0.998135
2025-11-26 18:45:00 -0.773866  0.730625  1.790614  5.0  4.0       16  0.997564
2025-11-26 19:45:00 -0.709735  0.069013  0.142754  5.0  4.5       18  0.996917

In [40]:
df

                            A         B         C    D    E  E prime    cosine
2025-11-26 10:45:00  0.000000 -1.034299 -0.569374  5.0  0.0        0  1.000000
2025-11-26 11:45:00  0.960620  0.195759 -0.525286  5.0  0.5        2  0.999962
2025-11-26 12:45:00  0.713676 -0.345756  0.603780  5.0  1.0        4  0.999848
2025-11-26 13:45:00 -0.348682 -0.414287 -1.066185  5.0  1.5        6  0.999657
2025-11-26 14:45:00 -1.827368  0.026077 -0.646162  5.0  2.0        8  0.999391
2025-11-26 15:45:00  0.414432 -0.608723 -0.084327  5.0  2.5       10  0.999048
2025-11-26 16:45:00 -0.859137 -0.733867  0.286232  5.0  3.0       12  0.998630
2025-11-26 17:45:00 -0.723186 -0.248101  0.538455  5.0  3.5       14  0.998135
2025-11-26 18:45:00 -0.773866  0.730625  1.790614  5.0  4.0       16  0.997564
2025-11-26 19:45:00 -0.709735  0.069013  0.142754  5.0  4.5       18  0.996917

In [41]:
# something like df.drop('index_name') 
# would work but the type of index must be specificed, 
# in particular with DatetimeIndex
df.drop(pd.to_datetime("2025-11-26 18:45:00"))

                            A         B         C    D    E  E prime    cosine
2025-11-26 10:45:00  0.000000 -1.034299 -0.569374  5.0  0.0        0  1.000000
2025-11-26 11:45:00  0.960620  0.195759 -0.525286  5.0  0.5        2  0.999962
2025-11-26 12:45:00  0.713676 -0.345756  0.603780  5.0  1.0        4  0.999848
2025-11-26 13:45:00 -0.348682 -0.414287 -1.066185  5.0  1.5        6  0.999657
2025-11-26 14:45:00 -1.827368  0.026077 -0.646162  5.0  2.0        8  0.999391
2025-11-26 15:45:00  0.414432 -0.608723 -0.084327  5.0  2.5       10  0.999048
2025-11-26 16:45:00 -0.859137 -0.733867  0.286232  5.0  3.0       12  0.998630
2025-11-26 17:45:00 -0.723186 -0.248101  0.538455  5.0  3.5       14  0.998135
2025-11-26 19:45:00 -0.709735  0.069013  0.142754  5.0  4.5       18  0.996917

## Missing data

pandas primarily uses the value np.nan to represent missing data. It is by default not included in computations.

In [42]:
df_wNan = df[df>-0.5]
df_wNan

                            A         B         C    D    E  E prime    cosine
2025-11-26 10:45:00  0.000000       NaN       NaN  5.0  0.0        0  1.000000
2025-11-26 11:45:00  0.960620  0.195759       NaN  5.0  0.5        2  0.999962
2025-11-26 12:45:00  0.713676 -0.345756  0.603780  5.0  1.0        4  0.999848
2025-11-26 13:45:00 -0.348682 -0.414287       NaN  5.0  1.5        6  0.999657
2025-11-26 14:45:00       NaN  0.026077       NaN  5.0  2.0        8  0.999391
2025-11-26 15:45:00  0.414432       NaN -0.084327  5.0  2.5       10  0.999048
2025-11-26 16:45:00       NaN       NaN  0.286232  5.0  3.0       12  0.998630
2025-11-26 17:45:00       NaN -0.248101  0.538455  5.0  3.5       14  0.998135
2025-11-26 18:45:00       NaN  0.730625  1.790614  5.0  4.0       16  0.997564
2025-11-26 19:45:00       NaN  0.069013  0.142754  5.0  4.5       18  0.996917

In [43]:
# dropping raws with at least a Nan
df_wNan.dropna(how='any')

                            A         B        C    D    E  E prime    cosine
2025-11-26 12:45:00  0.713676 -0.345756  0.60378  5.0  1.0        4  0.999848

In [44]:
# getting a mask
df_wNan.isna()
#df_wNan.notna()

                         A      B      C      D      E  E prime  cosine
2025-11-26 10:45:00  False   True   True  False  False    False   False
2025-11-26 11:45:00  False  False   True  False  False    False   False
2025-11-26 12:45:00  False  False  False  False  False    False   False
2025-11-26 13:45:00  False  False   True  False  False    False   False
2025-11-26 14:45:00   True  False   True  False  False    False   False
2025-11-26 15:45:00  False   True  False  False  False    False   False
2025-11-26 16:45:00   True   True  False  False  False    False   False
2025-11-26 17:45:00   True  False  False  False  False    False   False
2025-11-26 18:45:00   True  False  False  False  False    False   False
2025-11-26 19:45:00   True  False  False  False  False    False   False

In [45]:
# filling missing data
df_wNan.fillna(value=0)

                            A         B         C    D    E  E prime    cosine
2025-11-26 10:45:00  0.000000  0.000000  0.000000  5.0  0.0        0  1.000000
2025-11-26 11:45:00  0.960620  0.195759  0.000000  5.0  0.5        2  0.999962
2025-11-26 12:45:00  0.713676 -0.345756  0.603780  5.0  1.0        4  0.999848
2025-11-26 13:45:00 -0.348682 -0.414287  0.000000  5.0  1.5        6  0.999657
2025-11-26 14:45:00  0.000000  0.026077  0.000000  5.0  2.0        8  0.999391
2025-11-26 15:45:00  0.414432  0.000000 -0.084327  5.0  2.5       10  0.999048
2025-11-26 16:45:00  0.000000  0.000000  0.286232  5.0  3.0       12  0.998630
2025-11-26 17:45:00  0.000000 -0.248101  0.538455  5.0  3.5       14  0.998135
2025-11-26 18:45:00  0.000000  0.730625  1.790614  5.0  4.0       16  0.997564
2025-11-26 19:45:00  0.000000  0.069013  0.142754  5.0  4.5       18  0.996917

Fill gaps forward or backward by propagating non-NA values forward or backward:

In [46]:
df_wNan.fillna(method='pad')

/tmp/ipykernel_61146/1387294891.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_wNan.fillna(method='pad')

                            A         B         C    D    E  E prime    cosine
2025-11-26 10:45:00  0.000000       NaN       NaN  5.0  0.0        0  1.000000
2025-11-26 11:45:00  0.960620  0.195759       NaN  5.0  0.5        2  0.999962
2025-11-26 12:45:00  0.713676 -0.345756  0.603780  5.0  1.0        4  0.999848
2025-11-26 13:45:00 -0.348682 -0.414287  0.603780  5.0  1.5        6  0.999657
2025-11-26 14:45:00 -0.348682  0.026077  0.603780  5.0  2.0        8  0.999391
2025-11-26 15:45:00  0.414432  0.026077 -0.084327  5.0  2.5       10  0.999048
2025-11-26 16:45:00  0.414432  0.026077  0.286232  5.0  3.0       12  0.998630
2025-11-26 17:45:00  0.414432 -0.248101  0.538455  5.0  3.5       14  0.998135
2025-11-26 18:45:00  0.414432  0.730625  1.790614  5.0  4.0       16  0.997564
2025-11-26 19:45:00  0.414432  0.069013  0.142754  5.0  4.5       18  0.996917

## Operations

Here comes the most relevant advantage of DataFrame. Operations on columns are extremly fast due to several intrinsic optimizations:

* They are implemented in C/Cython via NumPy.
* Pandas processes columns as contiguous memory arrays.
* Vectorized operations eliminate the need for slow Python loops.
* Efficient memory and cache utilization boost performance.

In [47]:
# Some statistics (mean() just as an example)
# raws
print (df.mean(axis=0),'\n')
# columns
print (df.mean(axis=1),'\n')

A         -0.315325
B         -0.236356
C          0.047050
D          5.000000
E          2.250000
E prime    9.000000
cosine     0.998915
dtype: float64

2025-11-26 10:45:00    0.628047
2025-11-26 11:45:00    1.304436
2025-11-26 12:45:00    1.710221
2025-11-26 13:45:00    1.667215
2025-11-26 14:45:00    1.935991
2025-11-26 15:45:00    2.602919
2025-11-26 16:45:00    2.813123
2025-11-26 17:45:00    3.295043
2025-11-26 18:45:00    3.963562
2025-11-26 19:45:00    3.999850
Freq: h, dtype: float64

In [48]:
# global operations on columns
df.apply(np.cumsum)

,A,B,C,D,E,E prime,cosine
2025-11-26 10:45:00,0.000000,-1.034299,-0.569374,5.0,0.0,0,1.000000
2025-11-26 11:45:00,0.960620,-0.838541,-1.094660,10.0,0.5,2,1.999962
2025-11-26 12:45:00,1.674296,-1.184297,-0.490879,15.0,1.5,6,2.999810
2025-11-26 13:45:00,1.325614,-1.598584,-1.557064,20.0,3.0,12,3.999467
2025-11-26 14:45:00,-0.501754,-1.572507,-2.203226,25.0,5.0,20,4.998858
2025-11-26 15:45:00,-0.087322,-2.181230,-2.287553,30.0,7.5,30,5.997906
2025-11-26 16:45:00,-0.946459,-2.915097,-2.001321,35.0,10.5,42,6.996536
2025-11-26 17:45:00,-1.669644,-3.163198,-1.462866,40.0,14.0,56,7.994670
2025-11-26 18:45:00,-2.443510,-2.432573,0.327747,45.0,18.0,72,8.992234
2025-11-26 19:45:00,-3.153245,-2.363560,0.470501,50.0,22.5,90,9.989152

In [49]:
df

                            A         B         C    D    E  E prime    cosine
2025-11-26 10:45:00  0.000000 -1.034299 -0.569374  5.0  0.0        0  1.000000
2025-11-26 11:45:00  0.960620  0.195759 -0.525286  5.0  0.5        2  0.999962
2025-11-26 12:45:00  0.713676 -0.345756  0.603780  5.0  1.0        4  0.999848
2025-11-26 13:45:00 -0.348682 -0.414287 -1.066185  5.0  1.5        6  0.999657
2025-11-26 14:45:00 -1.827368  0.026077 -0.646162  5.0  2.0        8  0.999391
2025-11-26 15:45:00  0.414432 -0.608723 -0.084327  5.0  2.5       10  0.999048
2025-11-26 16:45:00 -0.859137 -0.733867  0.286232  5.0  3.0       12  0.998630
2025-11-26 17:45:00 -0.723186 -0.248101  0.538455  5.0  3.5       14  0.998135
2025-11-26 18:45:00 -0.773866  0.730625  1.790614  5.0  4.0       16  0.997564
2025-11-26 19:45:00 -0.709735  0.069013  0.142754  5.0  4.5       18  0.996917

In [50]:
df.apply(lambda x: x.max() - x.min())

A           2.787988
B           1.764925
C           2.856799
D           0.000000
E           4.500000
E prime    18.000000
cosine      0.003083
dtype: float64

In [51]:
# syntax is as usual similar to that of numpy arrays
df['A']+df['B']

2025-11-26 10:45:00   -1.034299
2025-11-26 11:45:00    1.156378
2025-11-26 12:45:00    0.367920
2025-11-26 13:45:00   -0.762969
2025-11-26 14:45:00   -1.801292
2025-11-26 15:45:00   -0.194291
2025-11-26 16:45:00   -1.593004
2025-11-26 17:45:00   -0.971287
2025-11-26 18:45:00   -0.043240
2025-11-26 19:45:00   -0.640721
Freq: h, dtype: float64

Let's play it hard and load (in memory) a (relatively) large dataset

In [52]:
# WARNING! link in past notebook was wrong!, (if needed) get the right file from:
#!wget https://www.dropbox.com/s/xvjzaxzz3ysphme/data_000637.txt -P ~/data/

file_name="~/data/data_000637.txt"
data=pd.read_csv(file_name)
data.tail(10)

FileNotFoundError: [Errno 2] No such file or directory: '/home/luca/data/data_000637.txt'

Let's now do some operations among (elements of) columns

In [ ]:
# the one-liner killing it all
data['timens']=data['TDC_MEAS']*25/30+data['BX_COUNTER']*25

In [ ]:
data['timens']

In [ ]:
# the old slooow way
def conversion(data):
    result=[]
    for i in range(len(data)): 
        result.append(data.loc[data.index[i],'TDC_MEAS']*25/30.+data.loc[data.index[i],'BX_COUNTER']*25)
    return result

data['timens']=conversion(data)

For tasks on extremely large datasets, libraries like [Polars](https://docs.pola.rs) or [Dask](https://www.dask.org) can offer even faster alternatives by further parallelizing or optimizing columnar operations.

## Merge

pandas provides various facilities for easily combining together Series, DataFrame, and Panel objects with various kinds of set logic for the indexes and relational algebra functionality in the case of join / merge-type operations.

### Concat

concatenation (adding rows) is straightforward

In [ ]:
rdf = pd.DataFrame(np.random.randn(10, 4))
rdf

In [ ]:
# divide it into pieaces raw-wise
pieces = [rdf[:3], rdf[3:7], rdf[7:]]
pieces

In [ ]:
# put it back together
#pd.concat(pieces)

# indexes can be ignored
pd.concat(pieces, ignore_index=True)

# in case of dimension mismatch, Nan are added where needed

In [ ]:
# appending a single row (as a Series)
s = rdf.iloc[3]
rdf = pd.concat([rdf,s.to_frame().T], ignore_index=True)
rdf

### Merge/Join

SQL like operations on table can be performed on DataFrames. This is all rather sophisticated, refer to the [doc](https://pandas.pydata.org/pandas-docs/stable/merging.html#merging) for more info/examples.

#### Merging, Inner Join (default)

Only rows with matching id values are included:

In [ ]:
import pandas as pd

df1 = pd.DataFrame({'id': [1, 2, 3], 'name': ['Alice', 'Bob', 'Charlie']})
df2 = pd.DataFrame({'id': [2, 3, 4], 'age': [25, 30, 35]})

# Merge on the 'id' column
result = pd.merge(df1, df2, on='id')
print(result)

#### Merging, Left Join

A left join includes all rows from `df1` (left) and fills in `NaN` for missing matches in `df2`.

In [ ]:
result = pd.merge(df2, df1, on='id', how='left')
print(result)

#### Merging, Outer Join

An outer join includes all rows from both DataFrames, filling NaN for missing values

In [ ]:
result = pd.merge(df1, df2, on='id', how='outer')
print(result)

`join` is similar to `merge` but uses index as key and has 'Left' as default

In [ ]:
df1 = pd.DataFrame({'name': ['Alice', 'Bob', 'Charlie']}, index=[1, 2, 3])
df2 = pd.DataFrame({'age': [25, 30, 35]}, index=[2, 3, 4])

result = df1.join(df2)
print(result)

## Grouping

By “group by” we are referring to a process involving one or more of the following steps:

* Splitting the data into groups based on some criteria
* Applying a function to each group independently
* Combining the results into a data structure


Grouping is one of the most powerful and at the same time most sofisticated action you can perform with DataFrames. Mastering it is key for an effective usage of Pandas and vectorized data analysis. Reading the [documentation](https://pandas.pydata.org/pandas-docs/stable/user_guide/groupby.html) or going through a [tutorial](https://realpython.com/pandas-groupby/) is warmly recommended. 

Let's go through a few examples:

In [53]:
data = {
    'Category': ['A', 'B', 'A', 'B', 'A', 'C'],
    'Values': [10, 20, 30, 40, 50, 60]
}

df = pd.DataFrame(data)

# Group by 'Category' and calculate the sum
result = df.groupby('Category').sum()
print(result)

          Values
Category
A             90
B             60
C             60

In [54]:
# Multiple Aggregations
result = df.groupby('Category').agg(['sum', 'mean'])
print(result)

         Values
            sum  mean
Category
A            90  30.0
B            60  30.0
C            60  60.0

In [55]:
# Grouping by multiple columns
df = pd.DataFrame({'Category': ['A', 'A', 'B', 'B', 'C', 'C'],
                   'Type': ['X', 'Y', 'X', 'Y', 'X', 'Y'],
                   'Values': [10, 20, 30, 40, 50, 60]})

result = df.groupby(['Category', 'Type']).sum()
print(result)

               Values
Category Type
A        X         10
         Y         20
B        X         30
         Y         40
C        X         50
         Y         60

In [56]:
# Trasformations using groupby(): add group averages to DataFrame
df['Group_Avg'] = df.groupby('Category')['Values'].transform('mean')
print(df)

  Category Type  Values  Group_Avg
0        A    X      10       15.0
1        A    Y      20       15.0
2        B    X      30       35.0
3        B    Y      40       35.0
4        C    X      50       55.0
5        C    Y      60       55.0

In [57]:
# filtering
filtered = df.groupby('Category').filter(lambda x: x['Values'].sum() > 50)
print(filtered)

  Category Type  Values  Group_Avg
2        B    X      30       35.0
3        B    Y      40       35.0
4        C    X      50       55.0
5        C    Y      60       55.0

In [58]:
# custom aggregation with apply()
def custom_aggregation(group):
    return pd.Series({
        'Sum': group['Values'].sum(),
        'Max': group['Values'].max(),
        'Count': group['Values'].count()
    })

result = df.groupby('Category').apply(custom_aggregation)
print(result)

          Sum  Max  Count
Category
A          30   20      2
B          70   40      2
C         110   60      2

/tmp/ipykernel_61146/640594234.py:9: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  result = df.groupby('Category').apply(custom_aggregation)

In [ ]:
# splitting data into groups
grouped = df.groupby('Category')

for name, group in grouped:
    print(f"Group: {name}")
    print(group)

## Multi-indexing


Hierarchical / Multi-level indexing allows sophisticated data analysis on higher dimensional data. In essence, it enables you to store and manipulate data with an arbitrary number of dimensions in lower dimensional data structures like Series (1d) and DataFrame (2d).

In [ ]:
tuples = list(zip(['bar', 'bar', 'baz', 'baz', 'foo', 'foo', 'qux', 'qux'],
          ['one', 'two', 'one', 'two', 'one', 'two', 'one', 'two']))
multi_index = pd.MultiIndex.from_tuples(tuples, names=['first', 'second'])
print (multi_index,'\n')

s = pd.Series(np.random.randn(8), index=multi_index)
print (s)

In [ ]:
gdf = pd.DataFrame({'A' : ['foo', 'bar', 'foo', 'bar',
                          'foo', 'bar', 'foo', 'foo'],
                    'B' : ['one', 'one', 'two', 'three',
                           'two', 'two', 'one', 'three'],
                    'C' : np.random.randn(8),
                    'D' : np.random.randn(8)})
gdf

# it enables further features of the groupby method,
# e.g. when group-by by multiple columns
gdf.groupby(['A','B']).sum()

In [ ]:
# stack() method “compresses” a level in the DataFrame’s columns
gdf.groupby(['A','B']).sum().stack()

## Plotting

Just a preview, more on the next lab class!

In [ ]:
ts = pd.Series(np.random.randn(1000), index=pd.date_range('1/1/2000', periods=1000))
ts.cumsum().plot()

In [ ]:
import matplotlib.pyplot as plt

pdf=pd.DataFrame(np.random.randn(1000, 4), index=ts.index,columns=['A', 'B', 'C', 'D'])
pdf = pdf.cumsum()
plt.figure(); pdf.plot(); plt.legend(loc='best')